<?xml version="1.0"?>
<project
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
	xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.fib</groupId>
		<artifactId>fib-midbiz</artifactId>
		<version>${revision}</version>
	</parent>
	<artifactId>fib-bss</artifactId>
	<name>fib-bss</name>
	<url>http://maven.apache.org</url>
	<packaging>jar</packaging>

	<dependencies>
		<dependency>
			<groupId>com.fib</groupId>
			<artifactId>fib-midbiz-common</artifactId>
			<version>${revision}</version>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<source>25</source> <!-- 与项目 JDK 版本一致（JDK 8+） -->
					<target>25</target>
					<encoding>UTF-8</encoding>
					<!-- 注解处理器路径：必须配置 MapStruct（若用 Lombok 则放在前面） -->
					<annotationProcessorPaths>
						<!-- MapStruct 注解处理器（必须配置，版本与核心依赖一致） -->
						<path>
							<groupId>org.mapstruct</groupId>
							<artifactId>mapstruct-processor</artifactId>
							<version>${mapstruct}</version>
						</path>
					</annotationProcessorPaths>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>