spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: fangyh102034

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.fib.entity
  configuration:
    map-underscore-to-camel-case: true # 下划线转驼峰
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql
  global-config:
    db-config:
      insert-strategy: not_null
      update-strategy: not_null
      where-strategy: not_null