<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.fib</groupId>
        <artifactId>fib-ecny</artifactId>
        <version>0.0.1</version>
    </parent>
    <artifactId>fib-ecny-module</artifactId>
    <name>fib-ecny-module</name>
    <url>https://maven.apache.org</url>
    <packaging>pom</packaging>
    <modules>
        <module>fib-ecny-query</module>
        <module>fib-ecny-trans</module>
        <module>fib-ecny-wallet</module>
    </modules>
</project>
