<?xml version="1.0"?>
<project
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
        xmlns="http://maven.apache.org/POM/4.0.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.fib</groupId>
        <artifactId>fib-payment</artifactId>
        <version>0.0.1</version>
    </parent>
    <artifactId>fib-hvps</artifactId>
    <name>fib-hvps</name>
    <url>https://maven.apache.org</url>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>com.fib</groupId>
            <artifactId>fib-payment-common</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson-spring-boot-starter</artifactId>
            <version>4.1.0</version>
        </dependency>
    </dependencies>
</project>