DROP TABLE IF EXISTS communication_event;
CREATE TABLE communication_event  (
  pk_id BIGINT(20) NOT NULL COMMENT '主键编码',
  comm_event_id VARCHAR(20)  NOT NULL COMMENT '交流事件编号',
  comm_event_type_id VARCHAR(20)  NOT NULL COMMENT '交流事件类型',
  parent_comm_event_id VARCHAR(20)  COMMENT '上一级交流事件号',
  message_status VARCHAR(20)  NOT NULL COMMENT '报文状态',
  party_id_from VARCHAR(20)  NOT NULL DEFAULT '-1' COMMENT '发起机构',
  party_id_to VARCHAR(20)  NOT NULL DEFAULT '-1' COMMENT '接收机构',
  entry_date TIMESTAMP NOT NULL COMMENT '录入日期',
  datetime_started TIMESTAMP(0) NULL DEFAULT NULL COMMENT '开始时间',
  datetime_ended TIMESTAMP(0) NULL DEFAULT NULL COMMENT '结束时间',
  message_id VARCHAR(20)  NOT NULL COMMENT '报文标识号',
  message_type_code VARCHAR(20)  NOT NULL COMMENT '报文类型',
  message_content text  NULL COMMENT '报文内容',
  remarks VARCHAR(255)  COMMENT '备注',
  channel_serial_no VARCHAR(255)  NOT NULL COMMENT '渠道流水号',
  message_ref_num VARCHAR(20) COMMENT '通讯参考号',
  del_flag SMALLINT DEFAULT 0 COMMENT '删除标志',
  create_by BIGINT(20)  DEFAULT 0 COMMENT '创建人',
  create_dt TIMESTAMP  DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_by BIGINT(0)  DEFAULT 0 COMMENT '更新人',
  update_dt TIMESTAMP(0) COMMENT '更新时间',
  PRIMARY KEY (pk_id) 
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_bin COMMENT = '交流事件';