<?xml version="1.0"?>
<project
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
	xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.fib</groupId>
		<artifactId>fib-payment</artifactId>
		<version>${revision}</version>
	</parent>
	<artifactId>fib-payment-app</artifactId>
	<name>fib-payment-app</name>
	<url>http://maven.apache.org</url>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>
	<dependencies>
		<dependency>
			<groupId>com.fib</groupId>
			<artifactId>fib-payment-common</artifactId>
			<version>${revision}</version>
		</dependency>

		<dependency>
			<groupId>com.fib</groupId>
			<artifactId>fib-hvps</artifactId>
			<version>${revision}</version>
		</dependency>

		<dependency>
			<groupId>com.fib</groupId>
			<artifactId>fib-beps</artifactId>
			<version>${revision}</version>
		</dependency>

		<dependency>
			<groupId>com.fib</groupId>
			<artifactId>fib-ibps</artifactId>
			<version>${revision}</version>
		</dependency>

		<dependency>
			<groupId>com.fib</groupId>
			<artifactId>fib-ccb</artifactId>
			<version>${revision}</version>
		</dependency>

		<dependency>
			<groupId>com.fib</groupId>
			<artifactId>fib-netunion</artifactId>
			<version>${revision}</version>
		</dependency>

		<dependency>
			<groupId>com.fib</groupId>
			<artifactId>fib-dcep</artifactId>
			<version>${revision}</version>
		</dependency>

		<!-- Spring Boot 测试（可选） -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
		</dependency>

		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-core</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<!-- 指定启动类 -->
					<mainClass>com.fib.pay.app.PayApplication</mainClass>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>repackage</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>